language: node_js
cache:
  directories:
    - node_modules
branches:
   - only:
     - master
notifications:
  email: false
node_js:
  - '5'
  - '7'
  - '6'
before_script:
  - npm prune
script:
  - npm run test
  - npm run test:cov
  - npm run check:cov
  - npm run build
after_success:
  - npm run report:cov
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
